#server
server:
  servlet:
    context-path: /
  port: 80

#spring
spring:
  thymeleaf:
    prefix: classpath:/templates/pages/
    suffix: .html
  datasource:
    url: jdbc:mysql://127.0.0.1/tedu?useSSL=false&characterEncoding=utf8
    username: root
    password: root

#mybatis
mybatis-plus:
#  type-aliases-package: com.jt.pojo
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true


#logging
logging:
  level:
    com.lc: debug


